RaythosAircraft/Models/Inventory.cs
using System.ComponentModel.DataAnnotations;

namespace RaythosAircraft.Models
{
    public class Inventory
    {
        [Key]
        public int InventoryId { get; set; }

        [Required]
        public string ItemCode { get; set; }

        public string Name { get; set; }

        public string Category { get; set; }

        public string Img1 { get; set; }
        public Double Price { get; set; }
        public string Specifications { get; set; }

        public string Description { get; set; }

        public string Type { get; set; }
        public string Quality { get; set; }
        public DateTime Days { get; set; }
        public int Quantity { get; set; }

        public static implicit operator Inventory(string v)
        {
            throw new NotImplementedException();
        }
    }
}

RaythosAircraft/Controllers/AdminDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RaythosAircraft.Data;
using RaythosAircraft.Models;

namespace RaythosAircraft.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminDashboardController : Controller
    {
        private readonly RaythosAircraft_db_Context _context;

        public AdminDashboardController(RaythosAircraft_db_Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // Retrieve counts from the database
            int productCount = _context.Products.Count();
            int inventoryCount = _context.Inventory.Count();
            int orderCount = _context.Order.Count();
            //int paymentCount = _context.Payment.Count();

            // Create an instance of CountPanel and set the counts
            CountPanel countPanel = new CountPanel
            {
                ProductCount = productCount,
                InventoryCount = inventoryCount,
                // Set properties for other counts
                OrderCount = orderCount,
                //PaymentCount = paymentCount
            };

            // Pass the CountPanel instance to the view
            return View(countPanel);
        }
    }
}

RaythosAircraft/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

//A controller for providing option user user to add new roles
namespace RaythosAircraft.Controllers
{
    public class AppRolesController : Controller
    {
        //Creating a variable
        private readonly RoleManager<IdentityRole> _roleManager;

        //Creating a constructor
        public AppRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        //List all the roles created by users
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        //A Method to return a view
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //A Method to create a new Role
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            //Avoid duplicate role
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }
    }
}

RaythosAircraft/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RaythosAircraft.Data;
using RaythosAircraft.Models;

namespace RaythosAircraft.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InventoriesController : Controller
    {
        private readonly RaythosAircraft_db_Context _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public InventoriesController(RaythosAircraft_db_Context context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Inventory
        public async Task<IActionResult> Index(string SearchBy, string search)
        {
            if (SearchBy == "Category")
            {
                return View(await _context.Inventory.Where(x => x.Category == search || search == null).ToListAsync());
            }
            else
            {
                return View(await _context.Inventory.Where(x => x.Name.StartsWith(search) || search == null).ToListAsync());

            }
        }

        // GET: Inventory/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Inventory == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .FirstOrDefaultAsync(m => m.InventoryId == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InventoryId,ItemCode,Name,Category,Img1,Price,Specifications,Description,Type,Quality,Days,Quantity")] Inventory inventory, IFormFile img1)
        {
            // Check if an image was uploaded
            if (img1 != null && img1.Length > 0)
            {
                // Generate a unique file name for the image
                string newFileName1 = Guid.NewGuid().ToString();

                // Specify the directory where the images will be stored
                var upload = Path.Combine(_webHostEnvironment.WebRootPath, @"InventoryImage\inventories");

                // Get the file extension for the uploaded image
                var extension1 = Path.GetExtension(img1.FileName);

                // Save the uploaded image with its unique file name
                using (var fileStream1 = new FileStream(Path.Combine(upload, newFileName1 + extension1), FileMode.Create))
                {
                    img1.CopyTo(fileStream1);
                }

                // Set the file path in the Inventory object
                inventory.Img1 = "/InventoryImage/inventories/" + newFileName1 + extension1;
            }

            // Check if the model state is valid
            if (ModelState.IsValid)
            {
                try
                {
                    // Add the Inventory object to the context and save changes
                    _context.Add(inventory);
                    await _context.SaveChangesAsync();

                    // Redirect to the Index action after successful creation
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Log or handle the exception as needed
                    ModelState.AddModelError("", "An error occurred while saving the inventory item.");
                }
            }

            // If ModelState is not valid, return the view with the model to display validation errors
            return View(inventory);
        }

        // GET: Inventory/Edit/5
        /*
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory.FindAsync(id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InventoryId,ItemCode,Name,Category,Img1,Price,Specifications,Description,Type,Quality,Days,Quantity")] Inventory updatedInventory, IFormFile newImg1)
        {
            if (id != updatedInventory.InventoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var originalInventory = await _context.Inventory.AsNoTracking().FirstOrDefaultAsync(p => p.InventoryId == id);

                    if (originalInventory == null)
                    {
                        return NotFound(); // Product not found
                    }

                    var imgPath1 = await HandleImageUpload(newImg1, originalInventory.Img1);

                    // Update properties in the updatedProduct object
                    updatedInventory.Img1 = imgPath1;



                    // Update other properties
                    _context.Update(updatedInventory);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InventoryExists(updatedInventory.InventoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return View(updatedProduct);
        }*/

        // GET: Iventory/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Inventory == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .FirstOrDefaultAsync(m => m.InventoryId == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // POST: Inventory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Inventory == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Products'  is null.");
            }
            var inventory = await _context.Inventory.FindAsync(id);
            if (inventory != null)
            {
                _context.Inventory.Remove(inventory);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

RaythosAircraft/Views/Inventories/Create.cshtml
@model RaythosAircraft.Models.Inventory

@{
    ViewData["Title"] = "Index";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>
    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />
    <style>
        .btn-custom {
            margin-right: 10px;
            border-radius: 10px;
            padding: 10px 20px;
        }
        .square-image {
            width: 100px;
            height: 100px;
        }
       
    </style>

</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15"></div>
                <div class="sidebar-brand-text mx-3">Raythos Aerospace</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Navigation Links -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="AdminDashboard" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- Add similar navigation links for other sections -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Products" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Product</span>
                </a>
            </li>
                         <li class="nav-item active">
               <a class="nav-link" asp-controller="Inventories" asp-action="Index">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Inventory</span>
               </a>
            </li>

             <li class="nav-item active">
               <a class="nav-link" asp-controller="Orders" asp-action="Index">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Order</span>
               </a>
            </li>
          
             <li class="nav-item active">
               <a class="nav-link" asp-controller="Users" asp-action="Index"> 
                <i class="fas fa-fw fa-tachometer-alt"></i> 
                <span>User</span> 
               </a>
            </li>

               <li class="nav-item active">
               <a class="nav-link" asp-controller="Payments" asp-action="Index"> 
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Payment</span> 
               </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-controller="AppRoles" asp-action="Index">
                    <i class="fas fa-users"></i>
                    <span>Roles Management</span>
                </a>
            </li>
            <!-- Add other navigation links here -->
        </ul>

        
   
    
<div id="content-wrapper" class="d-flex flex-column" style="margin-left:3px;"> <!-- Adjust the margin-left value as needed -->
    
        <!-- Topbar Navbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Your existing topbar content -->

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <!-- ... Your existing search dropdown content ... -->
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <!-- ... Your existing alerts dropdown content ... -->
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <!-- ... Your existing messages dropdown content ... -->
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                               <img  class="img-profile rounded-circle" src="~/img/undraw_profile.svg" />
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
    </ul>
</nav>

    <!-- Main Content -->
    <div id="content">
         
    <!-- Topbar Search -->

    <h4>Inventory</h4>
<hr />
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ItemCode" class="control-label"></label>
                    <input asp-for="ItemCode" class="form-control" />
                    <span asp-validation-for="ItemCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <input asp-for="Category" class="form-control" />
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
               <div class="form-group col-md-6">
                        <label asp-for="Img1" class="control-label"></label>
                        <input type="file" name="Img1" class="form-control" />
                        <span asp-validation-for="Img1" class="text-danger"></span>
                    </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Specifications" class="control-label"></label>
                    <input asp-for="Specifications" class="form-control" />
                    <span asp-validation-for="Specifications" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                    <label asp-for="Type" class="control-label"></label>
                    <input asp-for="Type" class="form-control" />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Quality" class="control-label"></label>
                    <input asp-for="Quality" class="form-control" />
                    <span asp-validation-for="Quality" class="text-danger"></span>
                </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label asp-for="Days" class="control-label"></label>
                        <input asp-for="Days" class="form-control" />
                        <span asp-validation-for="Days" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="Quantity" class="control-label"></label>
                        <input asp-for="Quantity" class="form-control" />
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>


<div>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>>



    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Core plugin JavaScript -->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages -->
    <script src="~/js/js/sb-admin-2.min.js"></script>

    @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }


</body>
</html>

RaythosAircraft/Views/Inventories/Delete.cshtml
@model RaythosAircraft.Models.Inventory

@{
    ViewData["Title"] = "Index";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>
    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />
    <style>
        .btn-custom {
            margin-right: 10px;
            border-radius: 10px;
            padding: 10px 20px;
        }
        .square-image {
            width: 100px;
            height: 100px;
        }
       
    </style>

</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15"></div>
                <div class="sidebar-brand-text mx-3">Raythos Aerospace</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Navigation Links -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="AdminDashboard" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- Add similar navigation links for other sections -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Products" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Product</span>
                </a>
            </li>
                         <li class="nav-item active">
               <a class="nav-link" asp-controller="Inventories" asp-action="Index">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Inventory</span>
               </a>
            </li>

             <li class="nav-item active">
               <a class="nav-link" asp-controller="Orders" asp-action="Index">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Order</span>
               </a>
            </li>
          
             <li class="nav-item active">
               <a class="nav-link" asp-controller="Users" asp-action="Index"> 
                <i class="fas fa-fw fa-tachometer-alt"></i> 
                <span>User</span> 
               </a>
            </li>

               <li class="nav-item active">
               <a class="nav-link" asp-controller="Payments" asp-action="Index"> 
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Payment</span> 
               </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-controller="AppRoles" asp-action="Index">
                    <i class="fas fa-users"></i>
                    <span>Roles Management</span>
                </a>
            </li>
            <!-- Add other navigation links here -->
        </ul>

        
   
    
<div id="content-wrapper" class="d-flex flex-column" style="margin-left:3px;"> <!-- Adjust the margin-left value as needed -->
    
        <!-- Topbar Navbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Your existing topbar content -->

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <!-- ... Your existing search dropdown content ... -->
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <!-- ... Your existing alerts dropdown content ... -->
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <!-- ... Your existing messages dropdown content ... -->
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                    <img  class="img-profile rounded-circle" src="~/img/undraw_profile.svg" />
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                </div>
            </li>
    </ul>
</nav>

    <!-- Main Content -->
    <div id="content">
         
    <!-- Topbar Search -->

    <h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Img1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Img1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specifications)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specifications)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Days)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Days)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InventoryId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
    </form>
</div>



    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Core plugin JavaScript -->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages -->
    <script src="~/js/js/sb-admin-2.min.js"></script>

    @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }


</body>
</html>